#!/bin/sh

cd Face_Enhancement/models/networks
git clone https://github.com/vacancy/Synchronized-BatchNorm-PyTorch
cp -rf Synchronized-BatchNorm-PyTorch/sync_batchnorm .
cd ../../../

cd Global/detection_models
git clone https://github.com/vacancy/Synchronized-BatchNorm-PyTorch
cp -rf Synchronized-BatchNorm-PyTorch/sync_batchnorm .
cd ../../

# download the landmark detection model
cd Face_Detection/
wget http://dlib.net/files/shape_predictor_68_face_landmarks.dat.bz2
bzip2 -d shape_predictor_68_face_landmarks.dat.bz2
cd ../

pip install gdown

# download the pretrained model
cd Face_Enhancement/
# fixed 404 The specified resource does not exist
# wget https://facevc.blob.core.windows.net/zhanbo/old_photo/pretrain/Face_Enhancement/checkpoints.zip
gdown 1EdkiHx8Cp_SZmbeFyk3YJj130kcE5-ds -O checkpoints.zip
unzip checkpoints.zip
cd ../

cd Global/
# wget https://facevc.blob.core.windows.net/zhanbo/old_photo/pretrain/Global/checkpoints.zip
gdown 1AAX6FJ4VjkQgEBDzNGiM1ebiECzywH5w -O checkpoints.zip
unzip checkpoints.zip
cd ../
